name: Generate Pokémon GO RSS

on:
  schedule:
    - cron: "0 6 * * *" # every day at 6am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scrapeduck-to-multi-rss.js

      - name: Copy RSS to docs
        run: |
          mkdir -p docs
          cp pogo-*.xml docs/

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update RSS feeds" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
